// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServerVer2.Models;

#nullable disable

namespace SqlServerVer2.Migrations.SamplePotDb
{
    [DbContext(typeof(SamplePotDbContext))]
    [Migration("20240515093846_initPot")]
    partial class initPot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlServerVer2.Models.Plant", b =>
                {
                    b.Property<string>("PlantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FlowerColor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FlowerTime")
                        .HasColumnType("int");

                    b.Property<int>("FruitingTime")
                        .HasColumnType("int");

                    b.Property<string>("LifeCycle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MinTemp")
                        .HasColumnType("int");

                    b.Property<int>("PhMaxVal")
                        .HasColumnType("int");

                    b.Property<int>("PhMinVal")
                        .HasColumnType("int");

                    b.Property<string>("PlantGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantHabit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlantHeight")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<int>("PlantWidth")
                        .HasColumnType("int");

                    b.Property<int>("SunReq")
                        .HasColumnType("int");

                    b.Property<string>("WaterPref")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlantName");

                    b.ToTable("Plant");
                });

            modelBuilder.Entity("SqlServerVer2.Models.Pot", b =>
                {
                    b.Property<int>("PotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PotId"));

                    b.Property<string>("PlantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PotType")
                        .HasColumnType("int");

                    b.HasKey("PotId");

                    b.HasIndex("PlantName")
                        .IsUnique();

                    b.ToTable("Pot");
                });

            modelBuilder.Entity("SqlServerVer2.Models.Pot", b =>
                {
                    b.HasOne("SqlServerVer2.Models.Plant", "Plant")
                        .WithOne()
                        .HasForeignKey("SqlServerVer2.Models.Pot", "PlantName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });
#pragma warning restore 612, 618
        }
    }
}
