// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLserverFinale.Models;

#nullable disable

namespace SQLserverFinale.Migrations
{
    [DbContext(typeof(PlantContext))]
    [Migration("20241118181152_PlantV1")]
    partial class PlantV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SQLserverFinale.Models.Plant", b =>
                {
                    b.Property<string>("PlantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FlowerColor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FlowerTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FruitingTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Humidity")
                        .HasColumnType("int");

                    b.Property<string>("LifeCycle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaxTemp")
                        .HasColumnType("int");

                    b.Property<int>("MinTemp")
                        .HasColumnType("int");

                    b.Property<int>("Nitrogen")
                        .HasColumnType("int");

                    b.Property<int>("PhMaxVal")
                        .HasColumnType("int");

                    b.Property<int>("PhMinVal")
                        .HasColumnType("int");

                    b.Property<int>("Phosphorus")
                        .HasColumnType("int");

                    b.Property<string>("PlantGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PlantHabit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlantHeight")
                        .HasColumnType("int");

                    b.Property<int>("PlantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlantId"));

                    b.Property<int>("PlantWidth")
                        .HasColumnType("int");

                    b.Property<int>("Potassium")
                        .HasColumnType("int");

                    b.Property<string>("SoilType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Spacing")
                        .HasColumnType("int");

                    b.Property<int>("SunReq")
                        .HasColumnType("int");

                    b.Property<string>("WaterPref")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlantName");

                    b.ToTable("Plant");
                });
#pragma warning restore 612, 618
        }
    }
}
